package us.physion.ovation.ui.browser;

import java.awt.Color;
import javax.swing.JButton;
import org.openide.awt.Actions;
import org.openide.explorer.view.BeanTreeView;

public final class FilteredTreeViewPanel extends javax.swing.JPanel {

    public FilteredTreeViewPanel(final String actionId, final String newEntityTooltip) {
        initComponents();

        newRootEntityLink.setToolTipText(newEntityTooltip);

        getTreeView().setRootVisible(false);
        getTreeView().setBackground(Color.white);

        newRootEntityLink.addActionListener(Actions.forID("Edit", actionId)::actionPerformed);
    }

    public BeanTreeView getTreeView() {
        return (BeanTreeView) treeView;
    }

    public JButton getNewRootEntityButton() {
        return newRootEntityLink;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        treeView = new BeanTreeView();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        newRootEntityLink = new org.jdesktop.swingx.JXHyperlink();

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setLeftComponent(treeView);

        jToolBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("NbExplorerView.background"));
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(javax.swing.UIManager.getDefaults().getColor("NbExplorerView.background"));
        jToolBar1.add(filler1);

        org.openide.awt.Mnemonics.setLocalizedText(newRootEntityLink, org.openide.util.NbBundle.getMessage(FilteredTreeViewPanel.class, "FilteredTreeViewPanel.newRootEntityLink.text")); // NOI18N
        newRootEntityLink.setFocusable(false);
        newRootEntityLink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newRootEntityLink.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newRootEntityLink);

        jSplitPane1.setRightComponent(jToolBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .add(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .add(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private org.jdesktop.swingx.JXHyperlink newRootEntityLink;
    private javax.swing.JScrollPane treeView;
    // End of variables declaration//GEN-END:variables
}
